wandb_version: 1

learning_rate:
  desc: null
  value: 0.05
architecture:
  desc: null
  value: Baseline
dataset:
  desc: null
  value: Image
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681284303.113227
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.14.2
      8:
      - 5
